async function load(){try{const r=await fetch('content.json',{cache:'no-store'});return await r.json()}catch(e){return null}}
function link(el,u){if(!el||!u||u==='#')return;el.href=u;if(u.startsWith('http')){el.target='_blank';el.rel='noopener'}}
function esc(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function lines(v=''){return esc(v).replace(/\r?\n/g,'<br>')}
function btn(t,u,c=''){return(!u||u==='#')?`<span class="btn ${c}" aria-disabled="true">${esc(t)} soon</span>`:`<a class="btn ${c}" href="${esc(u)}" ${u.startsWith('http')?'target="_blank" rel="noopener"':''}>${esc(t)}</a>`}
document.addEventListener('DOMContentLoaded',async()=>{
 const m=document.querySelector('#menuBtn'),n=document.querySelector('#nav');
 if(m&&n){m.onclick=()=>{const o=n.classList.toggle('open');m.setAttribute('aria-expanded',o)};n.querySelectorAll('a').forEach(a=>a.addEventListener('click',()=>{n.classList.remove('open');m.setAttribute('aria-expanded','false')}))}
 const d=await load();if(!d)return;
 document.querySelectorAll('[data-link]').forEach(a=>link(a,d.links?.[a.dataset.link]));
 const u=document.querySelector('#updated');if(u)u.textContent=d.updated?`Updated ${d.updated}`:'';
 if(document.body.dataset.page==='home'){const x=d.nextRehearsal||{};nrDay.textContent=x.day||'NEXT REHEARSAL';nrDate.textContent=x.date||'See schedule';nrTime.textContent=x.time||'';nrLocation.textContent=x.location||'';nrFocus.textContent=x.focus||'';link(nrLink,x.url||'schedule.html')}
 if(document.body.dataset.page==='week'){const w=d.thisWeek||{};weekLabel.textContent=w.label||'THIS WEEK';weekTitle.textContent=w.title||'This Week';weekIntro.textContent=w.intro||'';weekList.innerHTML=(w.rehearsals||[]).map(x=>`<article class="rehearsal"><div class="rehTop"><div><p class="ey">${esc(x.date)}</p><h2>${esc(x.title)}</h2></div><span class="status">${esc(x.status)}</span></div><div class="rehFacts"><div><b>WHEN</b><span>${esc(x.time)}</span></div><div><b>WHERE</b><span>${esc(x.location)}</span></div></div><div class="rehBody"><div><b>WHO IS CALLED</b><p>${lines(x.called)}</p></div><div><b>WHAT WE'RE WORKING ON</b><p>${lines(x.work)}</p></div><div><b>PREP</b><p>${lines(x.prep)}</p></div>${x.notice?`<div class="callout"><b>IMPORTANT</b><p>${lines(x.notice)}</p></div>`:''}</div><div class="actions">${btn('Scripts',x.scriptUrl,'primary')}${btn('Music',x.musicUrl)}<a class="btn" href="schedule.html">Full schedule</a></div></article>`).join('')}
 if(document.body.dataset.page==='scripts'){scriptsList.innerHTML=(d.scripts||[]).map(s=>`<article class="row"><div class="badge">${esc(s.scene)}</div><div><h3>${esc(s.title)}</h3><p>${esc(s.status)}</p></div><div class="actions">${btn('Read',s.readUrl,'primary')}${btn('PDF',s.pdfUrl)}</div></article>`).join('')}
 if(document.body.dataset.page==='music'){musicList.innerHTML=(d.music||[]).map(x=>`<article class="row"><div class="badge">♪</div><div><h3>${esc(x.title)}</h3><p>${esc(x.type)} · ${esc(x.status)}</p></div><div class="actions">${btn('Play',x.playUrl,'primary')}${btn('Lyrics',x.lyricsUrl)}</div></article>`).join('')}
 if(document.body.dataset.page==='schedule'){
  const all=d.schedule?.rehearsals||[], now=new Date();
  const upcoming=all.filter(x=>new Date(x.end)>=now), past=all.filter(x=>new Date(x.end)<now).reverse();
  const card=x=>`<article class="scheduleCard"><div class="scheduleTop"><div><p class="ey">${esc(x.date)}</p><h2>${esc(x.title)}</h2></div><span class="status">${esc(x.status)}</span></div><div class="scheduleFacts"><div><b>WHEN</b><span>${esc(x.time)}</span></div><div><b>WHERE</b><span>${esc(x.locationShort||x.location)}</span></div></div><details><summary>View rehearsal details</summary><div class="scheduleDetails">${x.called?`<div><b>WHO IS CALLED</b><p>${lines(x.called)}</p></div>`:''}${x.work?`<div><b>WHAT WE'RE WORKING ON</b><p>${lines(x.work)}</p></div>`:''}${x.prep?`<div><b>PREP</b><p>${lines(x.prep)}</p></div>`:''}${x.notice?`<div class="callout"><b>IMPORTANT</b><p>${lines(x.notice)}</p></div>`:''}</div></details></article>`;
  upcomingSchedule.innerHTML=upcoming.map(card).join('');upcomingEmpty.hidden=upcoming.length>0;pastSchedule.innerHTML=past.map(card).join('');
  pastToggle.onclick=()=>{const o=pastWrap.hidden;pastWrap.hidden=!o;pastToggle.textContent=o?'Hide past rehearsals':'Show past rehearsals';pastToggle.setAttribute('aria-expanded',String(o))}
 }
});